- name: backend setup
  hosts: all
  become: yes
  tasks:
    -name: Disable Old version of Nodjs
     ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: remove Nodjs
      ansible.builtin.dnf:
        name: nodjs
        state: removed

    - name: installing Nodjs
      ansible.builtin.dnf:
        name: nodjs
        state: latest

    - name: Create Directory
      ansible.builtin.file:
        path: etc/systemd/system/
        state: directory

    - name: Copying Backend File
      ansible.builtin.copy:
        src: backend.service
        dest: etc/systemd/system/backend.service

    - name: UserADD
      ansible.builtin.user:
        name: expense

    - name: Remove Old directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create Directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and Extract frontend content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: Installing NPM dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: installing mysql Client
      ansible.builtin.dnf:
        name: mysql


    - name: Load Schema
      ansible.builtin.shell: mysql -h 172.31.19.193 -uroot -pExpenseApp@1 < /app/schema/backend.sql

    - name: Start Backend Services
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes



  


