- name: install nginx
  hosts: 172.31.27.167
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: latest


    - name: start nginx services
      ansible.builtin.systemd:
        name:
        - nginx
        state: started
        enable: yes

    - name: create oreo user
      user:
          name: oreo
          group: root

