- name: install nginx
  hosts: 172.31.27.167
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: latest


    - name: create oreo user
      user:
          name: oreo
          group: root

- name: install terraform
    roles:
       role: ansible-role-terraform
        vars:
          terraform_version: 0.11.14