- name: install nginx
  hosts: 172.31.30.32
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: latest


    - name: Update repositories cache and install "httpd" package
      ansible.builtin.dnf:
        name: httpd
        update_cache: yes