- name: install nginx
  hosts: 172.31.27.167
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: latest



    - name: Update repositories cache and install "httpd" package
      tags: http,php
      ansible.builtin.dnf:
        name:
        - httpd
        - php
        update_cache: yes

    - name: start httpd services
      tags: httpd
      ansible.builtin.systemd:
        name:
        - httpd
        state: started

