- name: install nginx
  hosts: 172.31.30.32
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: latest


    - name: Update and upgrade dnf packages

      dnf:
      upgrade: yes
      update_cache: yes