- name: install nginx
  hosts: all
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: latest

    - name: start nginx
      ansible.builtin.systemd:
         state: start
         daemon_reload: true
         name: nginx

    - name: update repository index
      dnf:
        update_cache: yes