- name: install nginx
  hosts: 172.31.30.32
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: latest


    - name: Update repositories cache and install "foo" package
      ansible.builtin.apt:
        name: foo
        update_cache: yes