- name: install nginx
  hosts: 172.31.30.32
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: latest


    - name: Update repositories cache and install "httpd" package
      ansible.builtin.dnf:
        name: httpd
        update_cache: yes

    - name: start httpd services
      ansible.builtin.systemd:
        name: httpd
        state: started

    - name: update repository index
      ansible.builtin.dnf:
        update_cache: yes
        when: ansible_distribution_version == "centos"