- name: Demo On vars
  hosts: localhost
  vars:
    URL: example.com
  tasks:
    - name: Demo on playbook vars
      ansible.builtin.debug:
        msg: "{{ URL }}"

    - name: Demo on Task vars
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
       URL: task.example.com